services:
  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BACKEND_SERVICE_URL=http://microservice:8001
    depends_on:
      - microservice

  microservice:
    build:
      context: ./apps/microservice
      dockerfile: Dockerfile
    ports:
      - "8001:8001"